PAGES:
HOME - LOGIN - SIGNUP
WORKOUT TRACKER
NUTRUITION TRACKER
SLEEP TRACKER
TRAINING SCHEDULES
ABOUT
CONTACT
PRIVACY
TERMS
COOKIES

LOGIN PAGE:
MEMBER LOGIN - 
EMAIL ADDRESS
PASSWORD
FORGOT PASSWORD
SOCIAL LOGINS
REDIRECT TO SIGN UP IF NOT MEMBER

SIGNUP PAGE:
WELCOME PAGE -
"READY FOR SOME GAINS?"

CONTINUE -
DETAILS NEEDED:
NAME
GOALS (LOSE WEIGHT, MAINTAIN WEIGHT, GAIN WEIGHT, GAIN MUSCLE, MODIFY MY DIET, MODIFY MY WORKOUT)
AFFIRM USER, YOU'VE TAKEN A BIG STEP
MENTION GOALS CHOSEN

WHAT ARE YOUR GOALS FOR eg MUSCLE GAIN? (TONE UP, BULK UP, GET STRONG)
AFFIRM USER FOR THEIR GOALS

WHAT IS YOUR BASELINE ACTIVITY LEVEL? (NOT ACTIVE, LIGHTLY ACTIVE, MODERATELY ACTIVE, ACTIVE, VERY ACTIVE)

PERSONAL DETAILS:
SEX
DATE OF BIRTH
HEIGHT
WEIGHT & GOAL WEIGHT
LOCATION

ACCOUNT CREATION:
EMAIL ADDRESS
PASSWORD (AT LEAST 8 CHARACTERS, 1 NUMBER AND 1 ABSTRACT (@#$^&*!))
CONFIRM PASSWORD
RECAPTCHA
TERMS AND CONDITIONS & PRIVACY ACCEPTANCE
CONTINUE WITH EMAIL
OR SOCIAL LOGIN